apiVersion: apps/v1
kind: Deployment
metadata:
  name: wil42-deployment
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wil42-playground
  template:
    metadata:
      labels:
        app: wil42-playground
    spec:
      containers:
        - name: wil42-playground-container
          image: wil42/playground:v1
          ports:
            - containerPort: 8080
          env:
            - name: ENVIRONMENT
              value: "production"
